### ISSUE TITLE
Can you please provide the code for drawing Figure 1?

### ISSUE THREAD

**Issue by zhuzhenxi** [dvlab-research/MiSLAS#11]
Hi Zhisheng,
Thanks for your great work! Figure 1 in your paper is impressive, can you please provide the code for drawing this figure?

**Comment by zs-zhong** [comment]
Hi, thanks for your interest! I have uploaded the code: reliability_diagrams.py.  You can call the "reliability_diagrams" function to get the figure.

**Comment by zhuzhenxi** [comment]
This is really helpful. Thank you very much!
