### ISSUE TITLE
Access to models is limited in google drive

### ISSUE THREAD

**Issue by RobinVogel** [dvlab-research/MiSLAS#5]
Hello Zhisheng,

The access to the models is restricted by Google Drive (picture below, in French, translated below the picture). Could you make the models accessible to everyone?

PS: I may have sent you access requests, sorry about that.

Robin

![2021-06-02T12:12:37+02:00](https://user-images.githubusercontent.com/7306538/120463123-e12b7180-c39b-11eb-85b6-7af9489105ae.png)

Authorization is required
You need to request owner access or sign in with an account that has the necessary permissions. Find out more

**Comment by zs-zhong** [comment]
Hi Robin,

I am so sorry for the access authentication! I have fixed the access issue. Please try it again.

**Comment by RobinVogel** [comment]
Hi,

I have access to everything in incognito mode, thank you!
