### ISSUE TITLE
Regarding the test accuracy

### ISSUE THREAD

**Issue by KAISER1997** [dvlab-research/MiSLAS#7]
I hope I am not wrong. In the code I am seeing that you are calculating test accuracy after every few training iterations and taking the max of them.
My question was 
1) The results reported in the paper, Are they the maximum accuracy or the final accuracy after all the iterations?.
2) Is the validation same as test in cifar ?

**Comment by KingOfNorth77** [comment]
I have the same question. Can you please clarify 
@zs-zhong

**Comment by zs-zhong** [comment]
Hi,

Very thanks for your interest! In fact, there is no much difference for selecting models by the last epoch or taking the max of them in our experiments. Further, the code could achieve better accuracies than the results reported in the paper.

**Comment by KAISER1997** [comment]
Thanks for your reply,
Also regarding my second question I think both test and validation are taken to be the same.
My question is:
Have authors experimented using separate validation and test split?

**Comment by zs-zhong** [comment]
The CIFAR experiments are followed LDAM-DRW (https://github.com/kaidic/LDAM-DRW).

**Comment by KAISER1997** [comment]
Thanks . I will be closing this issue
